"""WhatsApp (Meta Cloud API) adapter for chat-py.

Python port of upstream ``packages/adapter-whatsapp``. Exposes
:class:`WhatsAppAdapter` plus helpers for thread-id encoding, webhook
verification, card-to-interactive-message translation, and a WhatsApp
markdown-flavoured format converter.
"""

from __future__ import annotations

from chat_adapter_whatsapp.adapter import (
    DEFAULT_API_BASE_URL,
    DEFAULT_API_VERSION,
    WHATSAPP_MESSAGE_LIMIT,
    WhatsAppAdapter,
    create_whatsapp_adapter,
    split_message,
)
from chat_adapter_whatsapp.cards import (
    WhatsAppCardInteractiveResult,
    WhatsAppCardResult,
    WhatsAppCardTextResult,
    card_to_plain_text,
    card_to_whatsapp,
    card_to_whatsapp_text,
    decode_whatsapp_callback_data,
    encode_whatsapp_callback_data,
)
from chat_adapter_whatsapp.errors import throw_whatsapp_api_error
from chat_adapter_whatsapp.markdown import (
    WhatsAppFormatConverter,
    from_whatsapp_format,
    to_whatsapp_format,
)
from chat_adapter_whatsapp.thread_id import (
    WhatsAppThreadId,
    channel_id_from_thread_id,
    decode_thread_id,
    encode_thread_id,
)
from chat_adapter_whatsapp.types import (
    WhatsAppAdapterConfig,
    WhatsAppApiErrorBody,
    WhatsAppApiErrorEnvelope,
    WhatsAppAudioPayload,
    WhatsAppButton,
    WhatsAppButtonPayload,
    WhatsAppButtonReply,
    WhatsAppButtonReplyAction,
    WhatsAppContact,
    WhatsAppContactProfile,
    WhatsAppContext,
    WhatsAppConversation,
    WhatsAppConversationOrigin,
    WhatsAppDocumentPayload,
    WhatsAppImagePayload,
    WhatsAppInboundMessage,
    WhatsAppInteractiveAction,
    WhatsAppInteractiveBody,
    WhatsAppInteractiveFooter,
    WhatsAppInteractiveHeader,
    WhatsAppInteractiveMessage,
    WhatsAppInteractivePayload,
    WhatsAppListReply,
    WhatsAppListRow,
    WhatsAppListSection,
    WhatsAppLocationPayload,
    WhatsAppMediaResponse,
    WhatsAppMessageType,
    WhatsAppMetadata,
    WhatsAppPricing,
    WhatsAppRawMessage,
    WhatsAppReactionPayload,
    WhatsAppSendContactEntry,
    WhatsAppSendMessageEntry,
    WhatsAppSendResponse,
    WhatsAppStatus,
    WhatsAppStickerPayload,
    WhatsAppTextPayload,
    WhatsAppVideoPayload,
    WhatsAppVoicePayload,
    WhatsAppWebhookChange,
    WhatsAppWebhookEntry,
    WhatsAppWebhookPayload,
    WhatsAppWebhookValue,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_API_BASE_URL",
    "DEFAULT_API_VERSION",
    "WHATSAPP_MESSAGE_LIMIT",
    "WhatsAppAdapter",
    "WhatsAppAdapterConfig",
    "WhatsAppApiErrorBody",
    "WhatsAppApiErrorEnvelope",
    "WhatsAppAudioPayload",
    "WhatsAppButton",
    "WhatsAppButtonPayload",
    "WhatsAppButtonReply",
    "WhatsAppButtonReplyAction",
    "WhatsAppCardInteractiveResult",
    "WhatsAppCardResult",
    "WhatsAppCardTextResult",
    "WhatsAppContact",
    "WhatsAppContactProfile",
    "WhatsAppContext",
    "WhatsAppConversation",
    "WhatsAppConversationOrigin",
    "WhatsAppDocumentPayload",
    "WhatsAppFormatConverter",
    "WhatsAppImagePayload",
    "WhatsAppInboundMessage",
    "WhatsAppInteractiveAction",
    "WhatsAppInteractiveBody",
    "WhatsAppInteractiveFooter",
    "WhatsAppInteractiveHeader",
    "WhatsAppInteractiveMessage",
    "WhatsAppInteractivePayload",
    "WhatsAppListReply",
    "WhatsAppListRow",
    "WhatsAppListSection",
    "WhatsAppLocationPayload",
    "WhatsAppMediaResponse",
    "WhatsAppMessageType",
    "WhatsAppMetadata",
    "WhatsAppPricing",
    "WhatsAppRawMessage",
    "WhatsAppReactionPayload",
    "WhatsAppSendContactEntry",
    "WhatsAppSendMessageEntry",
    "WhatsAppSendResponse",
    "WhatsAppStatus",
    "WhatsAppStickerPayload",
    "WhatsAppTextPayload",
    "WhatsAppThreadId",
    "WhatsAppVideoPayload",
    "WhatsAppVoicePayload",
    "WhatsAppWebhookChange",
    "WhatsAppWebhookEntry",
    "WhatsAppWebhookPayload",
    "WhatsAppWebhookValue",
    "__version__",
    "card_to_plain_text",
    "card_to_whatsapp",
    "card_to_whatsapp_text",
    "channel_id_from_thread_id",
    "create_whatsapp_adapter",
    "decode_thread_id",
    "decode_whatsapp_callback_data",
    "encode_thread_id",
    "encode_whatsapp_callback_data",
    "from_whatsapp_format",
    "split_message",
    "throw_whatsapp_api_error",
    "to_whatsapp_format",
]
